### ISSUE TITLE
Finance : Trend by Account

### ISSUE THREAD

**Issue by afs1jes** [afs1jes/CHNCT-Migration#30] opened 2019-12-31 19:22 UTC

**Comment by csoroka** [comment] 2020-04-23 15:59
Can you take a look at the total columns in drilling down to budget?  They don't seem to be adding up all the columns where the monthly amounts are showing.  Ran for Org Budget and for Revised Budget.  Also the data isn't protected as it is within other reports for the budget itemization.
Drilling into Actual - Can the amount column be formatted as currency?

Thank you,
Chrissy

**Comment by afs1jes** [comment] 2020-05-05 23:13
I removed the formulas from the Qtrs and Full Year columns (it's a report, so no need to calculate these columns).  The new Itemizations process uses the formatting and formulas of the originating sheet when setting up the itemization sheet, so it was inheriting those formulas but, because we omitted the Qtr columns from the itemization sheet, the formula for Full Year was no longer correct (it just added the 4 columns to the left). Anyway, that should be better now.

**Comment by csoroka** [comment] 2020-05-08 15:59
Christina Soroka has created a secure e-mail message for you at:

https://ssl.datamotion.com/r.aspx?b=16&eh=ipR3Tspzg0WlaVkNIKJL5A&cb=chnct1

To access your message, simply follow these steps:

1. Click on the above link. 
2. You will be prompted to create a password to protect your account.
3. Access your Inbox to view your message.


If you are unable to open the link, please make sure that your firewall or your company's security settings are not blocking the link.


Additional Help:
•		Questions relating to the content of the e-mail should be directed to the sender or sending organization.
•		Questions relating to reading this secure message can be sent to helpdesk@chnct.org.


--------------------------------------------------------------------------------
Message Details: 
Subject: RE: [afs1jes/CHNCT-Migration] Finance : Trend by Account (#30) 
From: csoroka@chnct.org 
To: reply@reply.github.com 
Created: 5/8/2020  11:59:40 AM (UTC-04:00:00) 
Message Expires: 8/8/2020  11:59:40 AM (UTC-04:00:00)

Copyright (c) 1996-2020 DataMotion, Inc.

**Comment by afs1jes** [comment] 2020-05-08 19:55
There was a bug in the A3 Player for a little while on Wednesday. Could you make sure that you have version 2020.05.07.01 or later?  If not, you can update the add-in via the Connect button on the A3 ribbon you currently have.
 
If you still have the problem, please use me know.

Jim

**Comment by csoroka** [comment] 2020-10-21 12:53
Ran this report for the 2019 Org & Rev Budgets.  When drilling into the LID for the Budget rows in account row for a month I noticed that the layout of the drill down does not mirror the Variance Explanations drill down (which is accurate)  can you please update the drill down to display the same?
I also ran this report for the 2019 Actuals - On the transactions tab I noticed that the Period field isn't showing up accurately when I drill into the Quarter or YTD it displays the first month of the first row in the list.  It does reflect the actual column I'm drilling into (i.e. "2nd Quarter" or "YTD") if this can't happen I would rather just hide that field.
Thank you

**Comment by afs1jes** [comment] 2020-10-22 16:17
I've changed the formula that presents the selected period... not yet fully tested, but appears better for Qtrs.

**Comment by afs1jes** [comment] 2020-10-27 22:31
I've removed (renamed) the specially format Sheed for transactions and the report should now use the default formatting, which will look more like the formatting on the variance explanations report.

This report is ready for another look.

**Comment by csoroka** [comment] 2020-10-29 13:32
Christina Soroka has created a secure e-mail message for you at:
https://ssl.datamotion.com/r.aspx?b=16&eh=M9njn0m540SSDX1s-qEh8g&cb=chnct1

To access your message, simply follow these steps:

1. Click on the above link. 
2. You will be prompted to create a password to protect your account.
3. Access your Inbox to view your message.

Problems accessing the message?
- If you are unable to open the link, please make sure that your firewall or your company's security settings are not blocking the link.
- If you are unsure of your password, please reset it at https://ssl.datamotion.com/ by clicking on the "Click HERE to reset your password" link.

Additional Help:
•		Questions relating to the content of the e-mail should be directed to the sender or sending organization.
•		Questions relating to reading this secure message can be sent to helpdesk@chnct.org.


--------------------------------------------------------------------------------
Message Details: 
Subject: RE: [afs1jes/CHNCT-Migration] Finance : Trend by Account (#30) 
From: csoroka@chnct.org 
To: reply@reply.github.com 
Message ID: 50740701
Created: 10/29/2020  9:32:46 AM (UTC-04:00:00) 
Expires: 1/29/2021  9:32:46 AM (UTC-04:00:00)
--------------------------------------------------------------------------------
Copyright (c) 1996-2020 DataMotion, Inc.

**Comment by afs1jes** [comment] 2020-10-29 13:43
**comment copied from secure mail**:
There is an issue the YTD on the Actual/Totals roll for the Itemized Drill down – please see drill down from current system attached.
The total in the new system is
 $302,.456
I also noticed when I went to double check the input tab, after I drilled down, that total changed even thought it was correct initially.

Thank you,
Chrissy

**Comment by csoroka** [comment] 2020-11-03 13:40
Any update on this?

**Comment by afs1jes** [comment] 2020-11-17 23:11
I believe that this is a bug in the process, but I've found a work-around (remove the Itemization Group markers from the template file).  You should see better results now.

**Comment by csoroka** [comment] 2020-11-18 15:39
Hello Jim -
It seems that the layout of the itemized details have changed since I ran the template on 10/29/2020 (see attached), not sure if this was part of the work around.  Can it please be changed back?
See the attached from when I ran my test.

Thank you,
Chrissy

**Comment by csoroka** [comment] 2021-01-21 16:01
Hello Jim - What is the status on this fix?

**Comment by afs1jes** [comment] 2021-01-25 21:28
The itemizations on this template uses the new default "report" process for itemizations, giving you a filterable / sortable / read-only list of the itemizations submitted from the input model(s).  In this non-updatable itemization sheet, it's much easier to skip the Qtr columns, but I think that's the only change that was made.  If you could send me the file, I can take a look at what other changes were made.

**Comment by csoroka** [comment] 2021-01-26 14:16
Hello Jim -
Is it possible to make some of the columns smaller and hide a couple?  The issue is with the freeze panes it is hard to see the monthly and YTD numbers on the template, via the monitor.  
Can we hide column J & M?  These two columns (Adjustment & Scenario) should be repetitive in ever row when you are drilling into itemized detail and are listed on the top row 4.  
Also if we can make columns I, K and L (Account Name, LOB and Org Name) smaller?  Col I (6 width), Col K (3.5 width) and Col L (4 width)

Thank you for hiding the quarters.

-Chrissy

**Comment by kclark-a3** [comment] 2022-02-28 22:57
- Template itemizations and transactions

**Comment by csoroka** [comment] 2022-04-27 14:42
Did testing for the following - Total CHN & CHNCT for 2022 Org Budget, 01-610 2022 Org Budget, 01-610 2022 Actuals & 01-610 2021 Revised Budget.

Found the following issues:

1) Input tab for all reports did not have the scenario listed on the top left under the CHN logo
2) The LID drill down doesn't have the same formatting as the LID templates that were emailed to us on 4/13/2022, which were approved
3) When drilling down into GL Details for the 2022 Actuals report, additional blank pages are being printed
4) The 2021 Revised Budget report doesn't look accurate regarding the column headers on the input tab (August - December) should state "Budget" and not "Actuals"
5) The 2021 Revised Budget drill down of LID formatting doesn't look accurate as the column headers are incorrect for August forward along with the shading.  In addition there is not sort # column.

**Comment by kclark-a3** [comment] 2022-04-28 01:30
Updates for items below: 

1. Input tab for all reports did not have the scenario listed on the top left under the CHN logo **scenario was added**
2. The LID drill down doesn't have the same formatting as the LID templates that were emailed to us on 4/13/2022, which were approved **LID is all grey as white cells indicate that they are editable; cell wrapping and number format updated and 'DisplayOrder' column is no longer hidden.**
3. When drilling down into GL Details for the 2022 Actuals report, additional blank pages are being printed **pending**
4. The 2021 Revised Budget report doesn't look accurate regarding the column headers on the input tab (August - December) should state "Budget" and not "Actuals" **fixed**
5. The 2021 Revised Budget drill down of LID formatting doesn't look accurate as the column headers are incorrect for August forward along with the shading. In addition there is not sort # column. **fixed**

**Comment by kclark-a3** [comment] 2022-04-28 23:34
Trend by Account is now ready for testing by CHN

3. When drilling down into GL Details for the 2022 Actuals report, additional blank pages are being printed **fixed**

**Comment by csoroka** [comment] 2022-05-02 20:27
Hello - I ran the Trend by Account for 01-610 and all the row came up blank.  (see attached
[Trend Report 2021 Revised Budget_for 01 - Corporate 610 - IS Technical Svcs (1).pdf](https://github.com/afs1jes/CHNCT-Migration/files/8605829/Trend.Report.2021.Revised.Budget_for.01.-.Corporate.610.-.IS.Technical.Svcs.1.pdf)
)

**Comment by afs1jes** [comment] 2022-05-04 15:58
Testing e-mail notification

**Comment by csoroka** [comment] 2022-05-05 19:08
Hello - I ran the Trend by Account for 01-610 2021 Revised Budget and found the following:

- On the Data and LID tabs Jan-Jul are not marked as "Actuals" (actuals for those months were used for the revised budget and the managers keyed in LID data for August - December 2021)  see the attachment of the way it looks in current prod
- Is it possible to hide the comments column on the data tab (they are not used at this time)
- I assume once the month headers are corrected (actuals vs budget), then the LID drill down shading will be similar to what is attached?
- The LID monthly column totals are not accurate (see attached) but the data tab monthly amounts are correct
[Trend by Account - current prod 04272022.pdf](https://github.com/afs1jes/CHNCT-Migration/files/8634612/Trend.by.Account.-.current.prod.04272022.pdf)

**Comment by kclark-a3** [comment] 2022-05-09 20:48
1. On the Data and LID tabs Jan-Jul are not marked as "Actuals" (actuals for those months were used for the revised budget and the managers keyed in LID data for August - December 2021) see the attachment of the way it looks in current prod. **I submitted the actuals flags for Jan-Jul**
2. Is it possible to hide the comments column on the data tab (they are not used at this time) **done**
3. I assume once the month headers are corrected (actuals vs budget), then the LID drill down shading will be similar to what is attached? **yes**
4. The LID monthly column totals are not accurate (see attached) but the data tab monthly amounts are correct **in progress**

**Comment by kclark-a3** [comment] 2022-05-12 19:37
Update

The LID monthly column totals are not accurate (see attached) but the data tab monthly amounts are correct  **this was fixed**

Template is ready for testing.

**Comment by csoroka** [comment] 2022-05-23 21:01
Ran - 2022 Actual Trend report for 01-610 and when drilling into 5430 there was no results for GL Transactions

**Comment by kclark-a3** [comment] 2022-05-24 04:27
Transactions were copied and can now be drilled into.

**Comment by csoroka** [comment] 2022-05-24 20:23
Looks good

**Comment by csoroka** [comment] 2022-05-31 14:13
Waiting to test again once the FAL, HLD & FDN line item details are uploaded

**Comment by csoroka** [comment] 2022-06-01 15:15
As discussed today on the call - I'm going to also use this template to test ALL budget/reporting scenarios in the current system against the new system to ensure that all the financial data and LID data came over.

**Comment by csoroka** [comment] 2022-06-22 14:33
Can you add LOB & Dept columns to the LID drill down?  It is helpful when we runt the report by LOB roll up as CHN or ASO as an example - then we can identify which rows below to which cost centers.
Thank you

**Comment by csoroka** [comment] 2022-06-22 14:36
The drill down the revised budget (totals) are not accurate. I ran it for the 2021 Revised Budget ASO for Total CHNCT
I also ran a report for 2021 Org Budget for ASO / Total CHNCT and drilled into 5260 to test and the totals didn't match the input tab which was very surprising.

**Comment by kclark-a3** [comment] 2022-06-22 20:12
Update

- LOB and dept are now displayed in the report

**Comment by csoroka** [comment] 2022-06-23 18:12
Thank you for adding LOB & Dept - I'm unable to sort the LID by Department code or any of the other columns

**Comment by csoroka** [comment] 2022-06-27 14:13
Per the email exchange we will not be unprotecting the worksheet to active the sort abilities we understand this would open the data to possibly get written back to the database.   Thank you

**Comment by csoroka** [comment] 2022-07-06 20:09
Please expand the account column on the LID drill down
Thank you

**Comment by csoroka** [comment] 2022-07-11 20:42
Thank you - this looks good

**Closed** 2022-07-25 18:56 UTC

**Comment by kclark-a3** [comment] 2022-10-11 08:41
Updates for items below.

 

1.         Input tab for all reports did not have the scenario listed on the top left under the CHN logo                        scenario was added to header

2.         The LID drill down doesn't have the same formatting as the LID templates that were emailed to us on 4/13/2022, which were approved

LID cells are grey in this report because white cells indicate that they are editable; ‘DisplayOrder’ column is now displayed; cell wrapping and number formatting were updated.

 

3.         When drilling down into GL Details for the 2022 Actuals report, additional blank pages are being printed pending

4.         The 2021 Revised Budget report doesn't look accurate regarding the column headers on the input tab (August - December) should state "Budget" and not "Actuals"       fixed

5.         The 2021 Revised Budget drill down of LID formatting doesn't look accurate as the column headers are incorrect for August forward along with the shading. In addition there is not sort # column.          fixed

 

 

- Keisha
